# Generated by Django 4.0.6 on 2022-07-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_contact_alter_post_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
